# Generated by Django 2.2.10 on 2021-02-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_model', models.CharField(max_length=30)),
                ('product_type', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('product_weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
