# Generated by Django 2.2.10 on 2021-02-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Individual_User',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Website',
            fields=[
                ('business_licence', models.IntegerField(primary_key=True, serialize=False)),
                ('web_address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('fax_number', models.IntegerField()),
                ('province', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('shipped_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Physical_Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fax_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('shipper_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shipper_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fax_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Web_Admin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_fname', models.CharField(max_length=255)),
                ('admin_lname', models.CharField(max_length=255)),
                ('admin_password', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('business_licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inventory_Website')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ShippedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
                ('shipper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Shipper')),
            ],
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Individual_User')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Individual_User')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Information_Page',
            fields=[
                ('page_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_description', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='individual_user',
            name='business_licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inventory_Website'),
        ),
        migrations.CreateModel(
            name='Has',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Support',
            fields=[
                ('cust_sup_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_sup_fname', models.CharField(max_length=255)),
                ('cust_sup_lname', models.CharField(max_length=255)),
                ('business_licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inventory_Website')),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_sup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Support')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Individual_User')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Physical_Store'),
            preserve_default=False,
        ),
    ]
