# Generated by Django 2.2.10 on 2021-03-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physical_store',
            options={'ordering': ['store_id']},
        ),
    ]
